name: Release to PSGallery

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-to-psgallery:
    name: Publish to PSGallery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish to PSGallery
        shell: pwsh
        run: Publish-Module -Path "${{ github.workspace }}/src/TcPrjMgmt" -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }}
